spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/zsx/mapper/*.xml   # Mapper XML文件路径
  type-aliases-package: com.zsx.pojo  # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true       # 启用下划线到驼峰命名的映射



